spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: ${SQL_password}
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql
server:
  port : 8080
#  error:
#    path: /user/error
#    whitelabel:
#      enabled: false

