spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: ${SQL_password}
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql
server:
  port : 8080
logging:
  level:
#    com.zaxxer.hikari: DEBUG
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.springframework.jdbc.datasource.DataSourceTransactionManager: TRACE
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

#  error:
#    path: /user/error
#    whitelabel:
#      enabled: false

